### ISSUE TITLE
Add real time plotting to UI

### ISSUE THREAD

**Issue by HanawuZ** [HanawuZ/nail-detection-2.0#25]
## Real Time Plotting
- ใช้ class `FuncAnimation`  จาก matplotlib มาใช้
- ให้กราฟทำการ plot ค่าความเข้มของเล็บแบบ real-time และทุกๆ ค่าเวลาหนึ่งก็จะเคลียข้อมูลอาเรย์ ให้มีพื้นที่ว่างพอ

### Tasks :bulb:
- [x] เพิ่มโค๊ดการทดสอบการ plot แบบ real time
- [x] เพิ่มฟังก์ชันการ plot แบบ real time จากคลิปที่อ่านมา
- [x] นำฟังก์ชันไปรวมกับ UI หลัก

**Comment by HanawuZ** [comment]
@Pet002 
มีปัญหาละ คือเขียนโค๊ดแสดงกราฟแบบ animation เข้าไปไม่ได้ พอแทรกเข้าไปแล้ว ภาพจากกล้องมันไม่ทำงานเฉยเลย งงมาก

**Comment by Pet002** [comment]
Push branch ขึ้นมาให้หน่อย ดียวจะลองดู อาจจะเป็นเพราะว่าทำ Multiprocess ไม่ได้รึป่าวนะ เดียวลองหาดูให้ๆ

**Comment by Pet002** [comment]
can you create new PR to github??

i will fix it.. 👍🏼
